version: '3.8'

services:
  auth_service:
    image: caothi/frontend_roadvision_classifier:latest
    container_name: frontend
    restart: always
    networks:
      - app_network

networks:
  app_network:
    external: true