if [ -n "${POSTGRES_USER_DEV}" ] && [ -n "${POSTGRES_PASSWORD_DEV}" ]; then
    echo "Creating user: ${POSTGRES_USER_DEV}"
    export PGPASSWORD="$POSTGRES_PASSWORD"
    psql -v ON_ERROR_STOP=1 --username "${POSTGRES_USER}" --dbname "${POSTGRES_DB}" <<-EOSQL
        CREATE USER "${POSTGRES_USER_DEV}" WITH PASSWORD '${POSTGRES_PASSWORD_DEV}';
        GRANT ALL PRIVILEGES ON DATABASE "${POSTGRES_DB}" TO "${POSTGRES_USER_DEV}";
EOSQL
else
    echo 'POSTGRES_USER_DEV or POSTGRES_PASSWORD_DEV is not set!'
fi