FROM postgres:14-alpine

ENV PG_CRON_VERSION=1.0.2

RUN \
  apk update && \
  apk upgrade && \
  apk add --no-cache postgresql-pg_cron=1.5.2-r0 --repository=https://dl-cdn.alpinelinux.org/alpine/v3.18/community;

RUN ln -s /usr/lib/postgresql15/pg_cron.so /usr/local/lib/postgresql/pg_cron.so && \
  ln -s /usr/share/postgresql15/extension/pg_cron* /usr/local/share/postgresql/extension

CMD [\
  "postgres",\
  "-c",\
  "shared_preload_libraries=pg_cron"\
]
